name: jessica-wilson-portfolio
recipe: pantheon
config:
  framework: wordpress
  site: jessica-wilson-portfolio
  id: aa71d241-596e-4bef-8708-cddb118ec6bb
colab:
  lando: 3.0.0-rc-12
  recipe: pantheon
  framework: wordpress
  version: 1.0.1
proxy:
  node:
    - 'sync-jessica-wilson-portfolio.lndo.site:3000'
services:
  node:
    type: 'node:custom'
    ssl: true
    overrides:
      ports:
        - '3000'
      image: 'colab/buildtools:node-8'
tooling:
  gulp:
    service: node
    description: Runs gulp commands
    cmd: gulp
  npm:
    service: node
    description: Runs npm commands
    cmd: npm
  prod:
    service: node
    description: '-- Runs production build of assets'
    cmd: cd $LANDO_MOUNT/wp-content/themes/jessica/ && npm install && npm run prod
  watch:
    service: node
    description: '-- Runs development build of assets and watch file changes'
    cmd: cd $LANDO_MOUNT/wp-content/themes/jessica/ && npm install && npm run watch
  xwatch:
    service: node
    description: Runs gulp watch
    cmd: cd $LANDO_MOUNT/wp-contet/themes/jessica/ && npm run watch
  yarn:
    service: node
    description: Runs yarn commands
    cmd: yarn
